#  Numpy 

NumPy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python. NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## 1 Creating array

### 1.1  Creating 0-D array

In [3]:
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))


42
<class 'numpy.ndarray'>


### 1.2  Creating 1-D array

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
#arr1=[1, 2, 3, 4, 5]
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


### 1.3  Creating 2-D array

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6,1]])

print(arr)
print(type(arr))
print((arr.ndim))
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr1.ndim)
print(type(arr1))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 1.4  Creating 3-D array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)
print(arr.shape)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(2, 2, 3)


In [ ]:
L=[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
print(L)

### 1.5  Check the of Dimension of Array

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


### 1.6 Access Array Elements

In [ ]:
#import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])   #adding 2nd and 3rd elements


1
2
7


### 1.7 Access 2-D array 

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st dim: ', arr[0, 1])
print('5th element on 2nd dim: ', arr[1, 4])
print( arr[0, 3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st dim:  2
5th element on 2nd dim:  10
4


### 1.8 Access 3-D array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 1, 0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
10


### 1.9 Negative Indexing

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[-1, -1])
#print('Last element from 2nd dim: ', arr[1, -1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


## 2 Array Slicing

In [ ]:
#[start:end].

# [start:end:step].

# If we don't pass start its considered 0

#If we don't pass end its considered length of array in that dimension

#If we don't pass step its considered 1

### 2.1 Slicing 1-D Array 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


### 2.2 Slicing 2-D

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])
print(arr[0:, 2]) #return index 2
print(arr[0:2, 1:4]) # slice index 1 to index 4 (not included)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]


# 3 Data Types in Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. eg. "ABCD"
- integer - used to represent integer numbers. eg. -1, -2, -3
- float - used to represent real numbers. eg. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j
**************************************************************************************
Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


### 3.1 Checking Data type of array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(type(arr))
print(arr.dtype)

arr1 = np.array(['apple', 'banana', 'cherry'])

print(arr1.dtype)


<class 'numpy.ndarray'>
int32
<U6


### 3.2 Creating Arrays with a defined Data Type

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
 
print(arr)
print(arr.dtype)
#arr1 = np.array(['a', '2', '3'], dtype='i') #Error


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')   # arr.astype(int)

print(newarr)
print(newarr.dtype)


In [ ]:
# Example 3:

import numpy as np

arr = np.array([1, 0,0,2, 3])

newarr = arr.astype(bool) # converting in Boolean

print(newarr)
print(newarr.dtype)


### 3.3 Copy and View

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
# The copy owns the data and any changes made to the copy will 
# not affect original array, and any #changes made to the 
# original array will not affect the copy.


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
x[1]=4

print(arr)
print(x)
#The view does not own the data and any changes made 
#to the view will affect the original array, and any 
#changes made to the original array will affect the view.


### 3.4 Get the shape of array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print(arr.shape)


### 3.5 Array Reshaping

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)  #1D to 2D

print(newarr)


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,2 ,2)  #1D to 3D

print(newarr)


In [ ]:
# Example 3:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)  # Error

print(newarr)


### 3.6 Iterating Arrays

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3]) #1D

for x in arr:
      print(x)

In [6]:
# Example 2:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  #2D

for x in arr:
    print(x)


[1 2 3]
[4 5 6]


In [7]:
# Example 3:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [8]:
# Example 4:
    
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   #3D

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### 3.7 Use of nditer()

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)


### 3.8 Using ndenumerate()

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)


In [ ]:
# Example 2:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print()

for idx, x in np.ndenumerate(arr):
    print(idx, x)


### 3.9 Joining array

In [ ]:
# Example 1:

#import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

print(arr1)

arr2 = np.array([[5, 6], [7, 8]])

print(arr2)

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


### 3.10 Splitting array

In [ ]:
# Example 1: 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3) # split into arrays

print(newarr[0])
print(newarr[1])
print(newarr[2])


### 3.11 Searching

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


In [ ]:
# Example 2: Finding where the values are even

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


### 3.12 Binary Search

In [ ]:
# Example 1:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [3,7]) #searching multiple values

print(x)


### 3.13 Sorting array

In [ ]:
# Example 1:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


In [ ]:
# Example 2:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


In [ ]:
# Example 3:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


### 3.14 Filter array

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, True]

newarr = arr[x]

print(newarr)

### 3.15 Random Numbers

In [ ]:
#Example 1: 

from numpy import random

x = random.randint(100)  #integer

print(x)

x1 = random.rand()     #Float
print(x1)


In [ ]:
# Example 2: Random array

from numpy import random

x=random.randint(100, size=(5))

print(x)

x1 = random.rand(5)

print(x1)


In [ ]:
# Example 3:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

x1 = random.rand(3, 5)
print(x1)


In [ ]:
# Example 4: Generate a random value based on an array of values.

from numpy import random

x = random.choice([3, 5, 7, 9])# size=(3, 5)

print(x)


### 3.16 Shuffle and Permutation

In [ ]:
# Example 1:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)


In [ ]:
# Example 2:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print(arr)#original array is unchanged


### 3.17 Arithmetic Operations

In [ ]:
# Example 1:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Add = Matrix_1 + Matrix_2

print(Add)


In [ ]:
# Example 2:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Subtract = Matrix_1 - Matrix_2

print(Subtract)

In [ ]:
# Example 3:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Multiply = Matrix_1 * Matrix_2

print(Multiply)


In [ ]:
# Example 4:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print("Original Matrix",Matrix_1)

Matrix_1.T
#Transpose of the Matrix_1.

In [ ]:
# Example 5:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print(Matrix_2)

print("Diagonal Values are: ", Matrix_2.diagonal())
#Accessing the diagonal of the Matrix_2.


In [ ]:
# Example 6:
    
Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print(Matrix_1)
print("Sum of diagonal elements is:", Matrix_1.trace())
#Returns the sum of diagonal elements of the Matrix_1.

In [ ]:
# Example 7:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

print(Matrix_2)
print("Maximum value is:", np.max(Matrix_2))
#Returns the maximum element of the matrix Matrix_2.


Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print(Matrix_1)
print("Minimum value is:",np.min(Matrix_1))
#Returns the minimum element of the Matrix_1.

In [ ]:
# Example 8:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print("Mean is:",np.mean(Matrix_2))
#It calculates the mean of the matrix.

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print("Variance is:",np.var(Matrix_2))
#It calculates the variance of the matrix.

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
print("Standard Deviation is:",np.std(Matrix_1))
#It calculates the standard deviation of the matrix.

## 4 Arithmetic Operations by using functions

In [ ]:

arr15 = np.array([[5,10],[15,20]])
arr16 = np.array([[6,12],[18,24]])
#Let us define 2 arrays.

print(arr15)
print(arr16)
print("Addition:",np.add(arr15,arr16))

print("Subtraction:",np.subtract(arr15,arr16))
#Subtraction of 2 arrays.

print("Division:",np.divide(arr15,arr16))
#Division of 2 arrays.

print("Multiplication:",np.multiply(arr15,arr16))
#Multiplication of 2 arrays.

print("Square Root:",np.sqrt(arr15))
#Returns the square root of the values in the array.


### 4.1 Remainder

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)    

print(newarr)


### 4.2 Power

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)    

print(newarr)


### 4.3 Absolute Value

In [ ]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)   #Absolute Values

print(newarr)


### 4.4 Trignometry Functions

In [ ]:
import numpy as np

arr16 = np.array([[6,12],[18,24]])
print(np.sin(arr16))
#Returns the trigonometric values of 'sin' applied on array 'arr16'.


arr15 = np.array([[5,10],[15,20]])
print(np.cos(arr15))

print(np.log(arr16))
#Returns the log value of the array 'arr16'.


### 4.5 Mean, Median, SD and Correlation

In [ ]:
arr15 = np.array([[5,10],[15,20]])

print(np.mean(arr15))
#This returns mean of the array.

arr16 = np.array([[6,12],[18,24]])
print(np.median(arr16))
#This returns the median of the array.


print(np.std(arr15))
#Returns the standard deviation of the array.

print(np.corr(arr15))
#Returns the correlation coefficient between the arrays.


### 4.6 Rounding Decimals

In [ ]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)


arr1 = np.fix([-3.1666, 3.6667]) #same as trunc()

print(arr1)


arr2 = np.around(3.1666, 2)

print(arr2)

arr3 = np.floor([-3.1666, 3.6667])

print(arr3)

arr4 = np.ceil([-3.1666, 3.6667])

print(arr4)


### 4.7 Log

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

print(np.log10(arr))


### 4.8 Summation and Addition

In [ ]:
# Example 1:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

newarr1 = np.sum([arr1, arr2], axis=1) #axis=0 means columns sum, 1 means rows sum
print(newarr1)

### 4.9 Product

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])  #newarr = np.prod([arr1, arr2], axis=1)

print(x)


### 4.10 Sets operation

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)  # find Union

print(newarr)


In [ ]:
# Example 3:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)  #intersection

print(newarr)


In [ ]:
# Example 4: difference

import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


#### Converting  Images to Numpy Arrays

<img src = "images/car-photo.png"/>

#### turning this image into numpy array

In [ ]:
from matplotlib.image import imread

panda = imread('images/panda.png')
print(type(panda))


<class 'numpy.ndarray'>


In [ ]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [ ]:
panda.shape

(2330, 3500, 3)

In [ ]:
panda.size

24465000